name: "PHP Style Linting"

on:
  pull_request:
  merge_group:

jobs:
  build_app:
    name: "PHPCS"
    runs-on: ubuntu-latest

    steps:
      - name: Skip
        run: echo 'workflow broke - skip for PR checks'
