name: PHP Compatibility Checks

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  php8-compatibility:
    name: PHP 8.x Compatibility
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: PHP Compatibility
        uses: pantheon-systems/phpcompatibility-action@bd72eb001d4fb9817c9d6e1a157a71e287f3ff80 # dev
        with:
          test-versions: 8.0-
          paths: ${{ github.workspace }}/*.php ${{ github.workspace }}/app/*.php ${{ github.workspace }}/admin/templates/partials/*.php
